module.exports = {
  apps: [
    // ── Frontend apps ──────────────────────────────────────────────────────
    {
      name: 'pos-admin-5173',
      cwd: './apps/admin',
      script: 'node_modules/vite/bin/vite.js',
      args: 'dev --port 5173',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        NODE_ENV: 'development',
        GATEWAY_URL: 'http://localhost:8000',
      },
    },
    {
      name: 'pos-cashier-5174',
      cwd: './apps/cashier',
      script: 'node_modules/vite/bin/vite.js',
      args: 'dev --port 5174',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        NODE_ENV: 'development',
        GATEWAY_URL: 'http://localhost:8000',
      },
    },

    // ── Go API gateway ─────────────────────────────────────────────────────
    {
      name: 'pos-gateway-8000',
      cwd: './services/api-gateway',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        HTTP_PORT: '8000',
        JWT_RS256_PUBLIC_KEY_PATH: '../../keys/public.pem',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        REDIS_DB: '0',
        AUTH_SERVICE_URL: 'localhost:8081',
        PRODUCT_SERVICE_URL: 'localhost:8082',
        INVENTORY_SERVICE_URL: 'localhost:8083',
        SALES_SERVICE_URL: 'localhost:8084',
        SUPPLIER_SERVICE_URL: 'localhost:8085',
        CUSTOMER_SERVICE_URL: 'localhost:8086',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },

    // ── Go backend services (infra via `make dev`) ─────────────────────────
    {
      name: 'pos-auth-8081',
      cwd: './services/auth-service',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        GRPC_PORT: '8081',
        METRICS_PORT: '9101',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'pos_db',
        POSTGRES_APP_PASSWORD: 'pos_db_stery',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        NATS_URL: 'nats://pos:pos-stery@localhost:4222',
        NATS_USER: 'pos',
        NATS_PASSWORD: 'pos-stery',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        JWT_RS256_PRIVATE_KEY_PATH: '../../keys/private.pem',
        JWT_RS256_PUBLIC_KEY_PATH: '../../keys/public.pem',
        OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },
    {
      name: 'pos-product-8082',
      cwd: './services/product-service',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        GRPC_PORT: '8082',
        METRICS_PORT: '9102',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'pos_db',
        POSTGRES_APP_PASSWORD: 'pos_db_stery',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        NATS_URL: 'nats://pos:pos-stery@localhost:4222',
        NATS_USER: 'pos',
        NATS_PASSWORD: 'pos-stery',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },
    {
      name: 'pos-inventory-8083',
      cwd: './services/inventory-service',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        GRPC_PORT: '8083',
        METRICS_PORT: '9103',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'pos_db',
        POSTGRES_APP_PASSWORD: 'pos_db_stery',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        NATS_URL: 'nats://pos:pos-stery@localhost:4222',
        NATS_USER: 'pos',
        NATS_PASSWORD: 'pos-stery',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },
    {
      name: 'pos-sales-8084',
      cwd: './services/sales-service',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        GRPC_PORT: '8084',
        METRICS_PORT: '9104',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'pos_db',
        POSTGRES_APP_PASSWORD: 'pos_db_stery',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        NATS_URL: 'nats://pos:pos-stery@localhost:4222',
        NATS_USER: 'pos',
        NATS_PASSWORD: 'pos-stery',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        INVENTORY_SERVICE_URL: 'localhost:8083',
        OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },
    {
      name: 'pos-supplier-8085',
      cwd: './services/supplier-service',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        GRPC_PORT: '8085',
        METRICS_PORT: '9105',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'pos_db',
        POSTGRES_APP_PASSWORD: 'pos_db_stery',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        NATS_URL: 'nats://pos:pos-stery@localhost:4222',
        NATS_USER: 'pos',
        NATS_PASSWORD: 'pos-stery',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        INVENTORY_SERVICE_URL: 'localhost:8083',
        OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },
    {
      name: 'pos-customer-8086',
      cwd: './services/customer-service',
      script: 'start.cjs',
      interpreter: 'C:/nvm4w/nodejs/node.exe',
      env: {
        GRPC_PORT: '8086',
        METRICS_PORT: '9106',
        POSTGRES_HOST: 'localhost',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'pos_db',
        POSTGRES_APP_PASSWORD: 'pos_db_stery',
        REDIS_ADDR: 'localhost:6379',
        REDIS_PASSWORD: 'redis',
        NATS_URL: 'nats://pos:pos-stery@localhost:4222',
        NATS_USER: 'pos',
        NATS_PASSWORD: 'pos-stery',
        SERVICE_TOKEN_SECRET: 'stery-secret',
        OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
        LOG_LEVEL: 'debug',
        ENVIRONMENT: 'development',
      },
    },
  ],
};
