// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, tenant_id, name, address, phone, is_active, created_at, updated_at
FROM auth.stores
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetStoreByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetStoreByIDRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Address   pgtype.Text
	Phone     pgtype.Text
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetStoreByID(ctx context.Context, arg GetStoreByIDParams) (GetStoreByIDRow, error) {
	row := q.db.QueryRow(ctx, getStoreByID, arg.ID, arg.TenantID)
	var i GetStoreByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, is_active, created_at, updated_at
FROM auth.tenants
WHERE id = $1 AND deleted_at IS NULL
`

type GetTenantByIDRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, tenant_id, email, password_hash, name, is_active, created_at, updated_at
FROM auth.users
WHERE email = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email    string
	TenantID uuid.UUID
}

type GetUserByEmailRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Auth service queries managed by sqlc.
// Run: cd services/auth-service && sqlc generate
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, is_active, created_at, updated_at
FROM auth.users
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetUserByIDRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT ur.role_id, r.name AS role_name, ur.store_id
FROM auth.user_roles ur
JOIN auth.roles r ON r.id = ur.role_id
WHERE ur.user_id = $1 AND ur.tenant_id = $2
`

type GetUserRolesParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

type GetUserRolesRow struct {
	RoleID   uuid.UUID
	RoleName string
	StoreID  *uuid.UUID
}

func (q *Queries) GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.StoreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeExistsInTenant = `-- name: StoreExistsInTenant :one
SELECT EXISTS(
    SELECT 1 FROM auth.stores
    WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
) AS store_exists
`

type StoreExistsInTenantParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) StoreExistsInTenant(ctx context.Context, arg StoreExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, storeExistsInTenant, arg.ID, arg.TenantID)
	var store_exists bool
	err := row.Scan(&store_exists)
	return store_exists, err
}
