// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthRole struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

type AuthStore struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Address   pgtype.Text
	Phone     pgtype.Text
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type AuthTenant struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type AuthUser struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type AuthUserRole struct {
	UserID   uuid.UUID
	RoleID   uuid.UUID
	StoreID  *uuid.UUID
	TenantID uuid.UUID
}
