// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth.refresh_tokens (
    id, user_id, tenant_id, family_id, token_hash, expires_at, user_agent, ip_address
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, tenant_id, family_id, token_hash, issued_at, expires_at,
          revoked_at, replaced_by, user_agent, ip_address, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TenantID  uuid.UUID
	FamilyID  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UserAgent string
	IpAddress string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRefreshTokenByHash = `-- name: FindRefreshTokenByHash :one
SELECT id, user_id, tenant_id, family_id, token_hash, issued_at, expires_at,
       revoked_at, replaced_by, user_agent, ip_address, created_at, updated_at
FROM auth.refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) FindRefreshTokenByHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByHash, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRefreshTokenByID = `-- name: FindRefreshTokenByID :one
SELECT id, user_id, tenant_id, family_id, token_hash, issued_at, expires_at,
       revoked_at, replaced_by, user_agent, ip_address, created_at, updated_at
FROM auth.refresh_tokens
WHERE id = $1
`

func (q *Queries) FindRefreshTokenByID(ctx context.Context, id uuid.UUID) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByID, id)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, tenant_id, family_id, token_hash, issued_at, expires_at,
       revoked_at, replaced_by, user_agent, ip_address, created_at, updated_at
FROM auth.refresh_tokens
WHERE user_id = $1 AND tenant_id = $2
  AND revoked_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListActiveSessionsByUserParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, arg ListActiveSessionsByUserParams) ([]AuthRefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthRefreshToken{}
	for rows.Next() {
		var i AuthRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.FamilyID,
			&i.TokenHash,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ReplacedBy,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE auth.refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE user_id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserTokensParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeAllUserTokens(ctx context.Context, arg RevokeAllUserTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, arg.UserID, arg.TenantID)
	return err
}

const revokeFamilyTokens = `-- name: RevokeFamilyTokens :exec
UPDATE auth.refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeFamilyTokens(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeFamilyTokens, familyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE auth.refresh_tokens
SET revoked_at = NOW(), replaced_by = $2, updated_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID         uuid.UUID
	ReplacedBy *uuid.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.ReplacedBy)
	return err
}
